#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by SmartEiffel The GNU Eiffel Compiler, Eiffel tools and libraries
Release 2.3 (Thursday July 11th 2007) [Antoine-Auguste Parmentier]
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER F.MERIZEN - SmartEiffel@loria.fr
http://SmartEiffel.loria.fr
C Compiler options used: -pipe
*/

#ifdef __cplusplus
}
#endif
#include "fibonacci.h"
#ifdef __cplusplus
extern "C" {
#endif

/*CHARACTER*/T6 r3is_equal(se_dump_stack*caller,T3 C,T3 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"is_equal"" CHARACTER",1,2,"%E3%other%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x04600F04/*l15c2/comparable.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x01A03608/*l54c4/any.e*/);
ac_req((a1,1),"other /= Void");
fd.assertion_flag=1;
}
(ds.p=0x04601108/*l17c4/comparable.e*/);
R=((T6)((T6)((r6_px_not(&ds,(T6)(r3_ix_60(&ds,C,a1))))&&((T6)(r6_px_not(&ds,(T6)(r3_ix_60(&ds,a1,C))))))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04601320/*l19c16/comparable.e*/);
ac_ens((R)==(r6_ix_and(&ds,(T6)(r6_px_not(&ds,(T6)(r3_ix_60(&ds,C,a1)))),(T6)(r6_px_not(&ds,(T6)(r3_ix_60(&ds,a1,C)))))),"trichotomy");
(ds.p=0x01A03972/*l57c57/any.e*/);
ac_ens((T6)((!(((T0*)(t[3]))==((void*)((T0*)(t[3])))))||((T6)((R)==(r3is_equal(&ds,a1,C))))),"commutative");
(ds.p=0x04801C16/*l28c11/hashable.e*/);
ac_ens((T6)((!(R))||((T6)((r3hash_code(&ds,C))==(r3hash_code(&ds,a1))))),"Result implies hash_code = other.hash_code");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3is_default(se_dump_stack*caller,T3 C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_default"" CHARACTER",1,1,"%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x01A08404/*l132c2/any.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x01A08D08/*l141c4/any.e*/);
R=((T6)((C)==(r3default(&ds))));
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T3 r3default(se_dump_stack*caller){
T3 R=0;
void**locals[1];
static se_frame_descriptor fd={"default"" CHARACTER",0,1,"Result%E3%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)0;
ds.p=0x01A07D12/*l125c9/any.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3_ix_6261(se_dump_stack*caller,T3 C,T3 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"infix "">="" (""infix "">="" CHARACTER)",1,2,"%E3%other%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00603F04/*l63c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04603E24/*l62c18/comparable.e*/);
ac_req((a1,1),"other_exists");
fd.assertion_flag=1;
}
(ds.p=0x00604208/*l66c4/character.e*/);
R=((T6)(((int16_t)(T3code(C)))>=(T3code(a1))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04604220/*l66c16/comparable.e*/);
ac_ens((R)==(r3_ix_6061(&ds,a1,C)),"definition");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3_ix_60(se_dump_stack*caller,T3 C,T3 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"infix ""<"" (""infix ""<"" CHARACTER)",1,2,"%E3%other%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00602B04/*l43c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04601B24/*l27c18/comparable.e*/);
ac_req((a1,1),"other_exists");
fd.assertion_flag=1;
}
(ds.p=0x00602E08/*l46c4/character.e*/);
R=((T6)(((int16_t)(T3code(C)))<(T3code(a1))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00603008/*l48c4/character.e*/);
ac_ens((R)==(((int16_t)(T3code(C)))<(T3code(a1))),"Result = (code < other.code)");
(ds.p=0x04601E2E/*l30c23/comparable.e*/);
ac_ens((T6)((!(R))||((T6)(r6_px_not(&ds,(T6)(r3_ix_60(&ds,a1,C)))))),"asymmetric");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3in_range(se_dump_stack*caller,T3 C,T3 a1,T3 a2){
T6 R=0;
void**locals[3];
static se_frame_descriptor fd={"in_range"" CHARACTER",1,3,"%E3%lower%E3%upper%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x04604504/*l69c2/comparable.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
locals[2]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x04604A08/*l74c4/comparable.e*/);
R=((T6)((T6)((r3_ix_6261(&ds,C,a1))&&((T6)(r3_ix_6061(&ds,C,a2))))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04604C08/*l76c4/comparable.e*/);
ac_ens((R)==(r6_ix_and(&ds,(T6)(r3_ix_6261(&ds,C,a1)),(T6)(r3_ix_6061(&ds,C,a2)))),"Result = (Current >= lower and Current <= upper)");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3_ix_6061(se_dump_stack*caller,T3 C,T3 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"infix ""<="" (""infix ""<="" CHARACTER)",1,2,"%E3%other%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00603304/*l51c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04602624/*l38c18/comparable.e*/);
ac_req((a1,1),"other_exists");
fd.assertion_flag=1;
}
(ds.p=0x00603608/*l54c4/character.e*/);
R=((T6)(((int16_t)(T3code(C)))<=(T3code(a1))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04602A20/*l42c16/comparable.e*/);
ac_ens((R)==(r6_ix_or(&ds,(T6)(r3_ix_60(&ds,C,a1)),(T6)(r3is_equal(&ds,C,a1)))),"definition");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T2 r3hash_code(se_dump_stack*caller,T3 C){
T2 R=0;
void**locals[1];
static se_frame_descriptor fd={"hash_code"" CHARACTER",1,1,"%E3%Result%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00615B04/*l347c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x00615D08/*l349c4/character.e*/);
R=/*IC*/(T2)(T3code(C));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04801638/*l22c28/hashable.e*/);
ac_ens(((int32_t)(R))>=(/*IC*/(T2)(INT8_C(0))),"good_hash_value");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3is_digit(se_dump_stack*caller,T3 C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_digit"" CHARACTER",1,1,"%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x0060AC04/*l172c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(((ds.p=0x0060B11E/*l177c15/character.e*/),r3_ix_6261(&ds,C,((T3)'0')))){
(ds.p=0x0060B20A/*l178c5/character.e*/);
R=((T6)(r3_ix_6061(&ds,C,((T3)'9'))));
}
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x0060B508/*l181c4/character.e*/);
ac_ens((R)==(r3in_range(&ds,C,((T3)'0'),((T3)'9'))),"Result = in_range(\'%/48/\', \'%/57/\')");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T1 r3value(se_dump_stack*caller,T3 C){
T1 R=0;
void**locals[1];
static se_frame_descriptor fd={"value"" CHARACTER",1,1,"%E3%Result%E1%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00604504/*l69c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00604808/*l72c4/character.e*/);
ac_req(r3is_digit(&ds,C),"is_digit");
fd.assertion_flag=1;
}
(ds.p=0x00604A08/*l74c4/character.e*/);
R=r1_ix_45(&ds,r10to_integer_8(&ds,T3code(C)),INT8_C(48));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00604C16/*l76c11/character.e*/);
ac_ens(r1in_range(&ds,R,INT8_C(0),INT8_C(9)),"Result.in_range(0, 9)");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T6 r3is_separator(se_dump_stack*caller,T3 C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_separator"" CHARACTER",1,1,"%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x0060F004/*l240c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
/*[INSPECT*/
{int inspect_tmp_1=((ds.p=0x0060F40A/*l244c5/character.e*/),C);
switch(inspect_tmp_1){
case 0:
case 9:
case 10:
case 12:
case 13:
case 32:
(ds.p=0x0060F60A/*l246c5/character.e*/);
R=((T6)(1));
break;
}
}/*INSPECT]*/
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*CHARACTER*/T1 r3decimal_value(se_dump_stack*caller,T3 C){
T1 R=0;
void**locals[1];
static se_frame_descriptor fd={"value"" CHARACTER",1,1,"%E3%Result%E1%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00604504/*l69c2/character.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00604808/*l72c4/character.e*/);
ac_req(r3is_digit(&ds,C),"is_digit");
fd.assertion_flag=1;
}
(ds.p=0x00604A08/*l74c4/character.e*/);
R=r1_ix_45(&ds,r10to_integer_8(&ds,T3code(C)),INT8_C(48));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00604C16/*l76c11/character.e*/);
ac_ens(r1in_range(&ds,R,INT8_C(0),INT8_C(9)),"Result.in_range(0, 9)");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/T6 r9all_default(se_dump_stack*caller,T9 C,T2 a1){
T6 R=0;
T2 _i=0;
T3 _v=0;
void**locals[4];
static se_frame_descriptor fd={"all_default"" NATIVE_ARRAY[CHARACTER]",1,4,"%E9%upper%E2%Result%E6%i%E2%v%E3%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x0722DF04/*l735c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
locals[2]=(void**)&_i;
locals[3]=(void**)&_v;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x0722E314/*l739c10/native_array.e*/);
ac_req(((int32_t)(a1))>=(/*IC*/(T2)(INT8_C(-1))),"upper >= -1");
fd.assertion_flag=1;
}
(ds.p=0x0722E80A/*l744c5/native_array.e*/);
R=((T6)(1));
(ds.p=0x0722E90A/*l745c5/native_array.e*/);
_i=a1;
while (!(((ds.p=0x0722EB16/*l747c11/native_array.e*/),(T6)((((int32_t)(_i))<(/*IC*/(T2)(INT8_C(0))))||((T6)(r6_px_not(&ds,(T6)(R))))))))
{
(ds.p=0x0722ED0A/*l749c5/native_array.e*/);
_v=(C)[_i];
if(((ds.p=0x0722EE10/*l750c8/native_array.e*/),(_v,1))){
(ds.p=0x0722EF0C/*l751c6/native_array.e*/);
R=((T6)(r3is_default(&ds,_v)));
}
(ds.p=0x0722F10A/*l753c5/native_array.e*/);
_i=r2_ix_45(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/void r9clear_all(se_dump_stack*caller,T9 C,T2 a1){
T3 _v=0;
T2 _i=0;
void**locals[3];
static se_frame_descriptor fd={"clear_all"" NATIVE_ARRAY[CHARACTER]",1,3,"%E9%upper%E2%v%E3%i%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07221D04/*l541c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&_v;
locals[2]=(void**)&_i;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07222014/*l544c10/native_array.e*/);
ac_req(((int32_t)(a1))>=(/*IC*/(T2)(INT8_C(-1))),"upper >= -1");
fd.assertion_flag=1;
}
(ds.p=0x0722250A/*l549c5/native_array.e*/);
_i=a1;
while (!(((ds.p=0x0722270E/*l551c7/native_array.e*/),((int32_t)(_i))<(/*IC*/(T2)(INT8_C(0))))))
{
(ds.p=0x0722290A/*l553c5/native_array.e*/);
(C)[_i]=(_v);
(ds.p=0x07222A0A/*l554c5/native_array.e*/);
_i=r2_ix_45(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07222D08/*l557c4/native_array.e*/);
ac_ens(r9all_default(&ds,C,a1),"all_default(upper)");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/T6 r9fast_has(se_dump_stack*caller,T9 C,T3 a1,T2 a2){
T6 R=0;
T2 _i=0;
void**locals[4];
static se_frame_descriptor fd={"fast_has"" NATIVE_ARRAY[CHARACTER]",1,4,"%E9%element%E3%upper%E2%Result%E6%i%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07215E04/*l350c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
locals[2]=(void**)&R;
locals[3]=(void**)&_i;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07216214/*l354c10/native_array.e*/);
ac_req(((int32_t)(a2))>=(/*IC*/(T2)(INT8_C(-1))),"upper >= -1");
fd.assertion_flag=1;
}
(ds.p=0x0721670A/*l359c5/native_array.e*/);
_i=a2;
while (!(((ds.p=0x07216916/*l361c11/native_array.e*/),(T6)((((int32_t)(_i))<(/*IC*/(T2)(INT8_C(0))))||((T6)((a1)==((C)[_i])))))))
{
(ds.p=0x07216B0A/*l363c5/native_array.e*/);
_i=r2_ix_45(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
(ds.p=0x07216D08/*l365c4/native_array.e*/);
R=((T6)(((int32_t)(_i))>=(/*IC*/(T2)(INT8_C(0)))));
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/T6 r9is_not_null(se_dump_stack*caller,T9 C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_not_null"" NATIVE_ARRAY[CHARACTER]",1,1,"%E9%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07231804/*l792c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x07231A08/*l794c4/native_array.e*/);
R=((T6)((NULL!=((void*)(C)))));
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/T6 r9is_null(se_dump_stack*caller,T9 C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_null"" NATIVE_ARRAY[CHARACTER]",1,1,"%E9%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07231D04/*l797c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x07231F08/*l799c4/native_array.e*/);
R=((T6)(r8is_null(&ds,((void*)(C)))));
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/T9 r9realloc(se_dump_stack*caller,T9 C,T2 a1,T2 a2){
T9 R=(void*)0;
void**locals[3];
static se_frame_descriptor fd={"realloc"" NATIVE_ARRAY[CHARACTER]",1,3,"%E9%old_nb_elts%E2%new_nb_elts%E2%Result%E9%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07203304/*l51c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
locals[2]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07203A08/*l58c4/native_array.e*/);
ac_req(r9is_not_null(&ds,C),"is_not_null");
(ds.p=0x07203B20/*l59c16/native_array.e*/);
ac_req(((int32_t)(a1))>(/*IC*/(T2)(INT8_C(0))),"old_nb_elts > 0");
(ds.p=0x07203C20/*l60c16/native_array.e*/);
ac_req(((int32_t)(a1))<(a2),"old_nb_elts < new_nb_elts");
fd.assertion_flag=1;
}
(ds.p=0x07203E08/*l62c4/native_array.e*/);
R=new9(a2);
(ds.p=0x07203F16/*l63c11/native_array.e*/);
r9copy_from(&ds,R,C,r2_ix_45(&ds,a1,/*IC*/(T2)(INT8_C(1))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07204116/*l65c11/native_array.e*/);
ac_ens(r9is_not_null(&ds,R),"Result.is_not_null");
fd.assertion_flag=1;
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*NATIVE_ARRAY[CHARACTER]*/void r9copy_from(se_dump_stack*caller,T9 C,T9 a1,T2 a2){
T2 _i=0;
void**locals[3];
static se_frame_descriptor fd={"copy_from"" NATIVE_ARRAY[CHARACTER]",1,3,"%E9%model%E9%upper%E2%i%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x07224204/*l578c2/native_array.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
locals[2]=(void**)&_i;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x07224514/*l581c10/native_array.e*/);
ac_req(((int32_t)(a2))>=(/*IC*/(T2)(INT8_C(-1))),"upper >= -1");
fd.assertion_flag=1;
}
(ds.p=0x07224A0A/*l586c5/native_array.e*/);
_i=a2;
while (!(((ds.p=0x07224C0E/*l588c7/native_array.e*/),((int32_t)(_i))<(/*IC*/(T2)(INT8_C(0))))))
{
(ds.p=0x07224E0A/*l590c5/native_array.e*/);
(C)[_i]=((a1)[_i]);
(ds.p=0x07224F0A/*l591c5/native_array.e*/);
_i=r2_ix_45(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/T6 r7is_default(se_dump_stack*caller,T7* C){
T6 R=0;
void**locals[1];
static se_frame_descriptor fd={"is_default"" STRING",1,1,"%R7%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x01A08404/*l132c2/any.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x01A08D08/*l141c4/any.e*/);
R=((T6)((C)==((void*)(r7default(&ds,C)))));
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/T0* r7default(se_dump_stack*caller,T7* C){
T0* R=(void*)0;
void**locals[1];
static se_frame_descriptor fd={"default"" STRING",1,1,"%R7%Result%R7%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x01A07D12/*l125c9/any.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/T6 r7is_integer(se_dump_stack*caller,T7* C){
T6 R=0;
T2 _i=0;
T2 _state=0;
T2 _value=0;
T2 _bound=0;
T2 _critical_bound=0;
T3 _cc=0;
void**locals[7];
static se_frame_descriptor fd={"is_integer"" STRING",1,7,"%R7%Result%E6%i%E2%state%E2%value%E2%bound%E2%critical_bound%E2%cc%E3%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E19E04/*l414c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
locals[1]=(void**)&_i;
locals[2]=(void**)&_state;
locals[3]=(void**)&_value;
locals[4]=(void**)&_bound;
locals[5]=(void**)&_critical_bound;
locals[6]=(void**)&_cc;
set_dump_stack_top(&ds);/*link*/
{int c=0;int v=0;
(ds.p=0x00E1B80A/*l440c5/string.e*/);
_i=/*IC*/(T2)(INT8_C(1));
while (!(((ds.p=0x00E1BC1E/*l444c15/string.e*/),(T6)(((_state)==(INT8_C(2)))||((T6)(((int32_t)(_i))>((/*RF2*/(C)->_count/*i3p*/))))))))
{
(ds.p=0x00E1BA16/*l442c11/string.e*/);
v=ac_lvc(c++,v,r2_ix_45(&ds,(/*RF2*/(C)->_count/*i3p*/),_i));
(ds.p=0x00E1BE0A/*l446c5/string.e*/);
_cc=r7item(&ds,C,_i);
/*[INSPECT*/
{int inspect_tmp_1=((ds.p=0x00E1C00C/*l448c6/string.e*/),_state);
switch(inspect_tmp_1){
case 0:
if(((ds.p=0x00E1C218/*l450c12/string.e*/),r3is_separator(&ds,_cc))){
}
else if(((ds.p=0x00E1C31A/*l451c13/string.e*/),(_cc)==(((T3)'\053')))){
(ds.p=0x00E1C40E/*l452c7/string.e*/);
_bound=((int32_t)(/*RF1Maximum_integer*/INT32_C(2147483647)))%(/*IC*/(T2)(INT8_C(10)));
(ds.p=0x00E1C50E/*l453c7/string.e*/);
_critical_bound=((int32_t)(/*RF1Maximum_integer*/INT32_C(2147483647)))/(/*IC*/(T2)(INT8_C(10)));
(ds.p=0x00E1C60E/*l454c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(1));
}
else if(((ds.p=0x00E1C71A/*l455c13/string.e*/),(_cc)==(((T3)'\055')))){
(ds.p=0x00E1C80E/*l456c7/string.e*/);
_bound=r2_px_45(&ds,((int32_t)(/*RF1Minimum_integer*/INT32_MIN))%(/*IC*/(T2)(INT8_C(10))));
(ds.p=0x00E1C90E/*l457c7/string.e*/);
_critical_bound=r2_px_45(&ds,((int32_t)(/*RF1Minimum_integer*/INT32_MIN))/(/*IC*/(T2)(INT8_C(10))));
(ds.p=0x00E1CA0E/*l458c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(1));
}
else if(((ds.p=0x00E1CB20/*l459c16/string.e*/),r3is_digit(&ds,_cc))){
(ds.p=0x00E1CC0E/*l460c7/string.e*/);
_bound=((int32_t)(/*RF1Maximum_integer*/INT32_C(2147483647)))%(/*IC*/(T2)(INT8_C(10)));
(ds.p=0x00E1CD0E/*l461c7/string.e*/);
_critical_bound=((int32_t)(/*RF1Maximum_integer*/INT32_C(2147483647)))/(/*IC*/(T2)(INT8_C(10)));
(ds.p=0x00E1CE0E/*l462c7/string.e*/);
_value=/*IC*/(T2)(r3decimal_value(&ds,_cc));
(ds.p=0x00E1CF0E/*l463c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(3));
}
else{
(ds.p=0x00E1D10E/*l465c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
break;
case 1:
if(((ds.p=0x00E1D418/*l468c12/string.e*/),r3is_digit(&ds,_cc))){
(ds.p=0x00E1D50E/*l469c7/string.e*/);
_value=/*IC*/(T2)(r3decimal_value(&ds,_cc));
(ds.p=0x00E1D60E/*l470c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(3));
}
else{
(ds.p=0x00E1D80E/*l472c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
break;
case 3:
if(((ds.p=0x00E1DB18/*l475c12/string.e*/),r3is_digit(&ds,_cc))){
(ds.p=0x00E1DC0E/*l476c7/string.e*/);
_value=r2_ix_43(&ds,r2_ix_42(&ds,/*IC*/(T2)(INT8_C(10)),_value),/*IC*/(T2)(r3decimal_value(&ds,_cc)));
if(((ds.p=0x00E1DD20/*l477c16/string.e*/),((int32_t)(_value))>=(_critical_bound))){
(ds.p=0x00E1DE10/*l478c8/string.e*/);
_state=/*IC*/(T2)(INT8_C(4));
}
}
else if(((ds.p=0x00E1E020/*l480c16/string.e*/),r3is_separator(&ds,_cc))){
(ds.p=0x00E1E10E/*l481c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(5));
}
else{
(ds.p=0x00E1E30E/*l483c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
break;
case 4:
if(((ds.p=0x00E1E618/*l486c12/string.e*/),r3is_digit(&ds,_cc))){
if(((ds.p=0x00E1E720/*l487c16/string.e*/),((int32_t)(_value))>(_critical_bound))){
(ds.p=0x00E1E810/*l488c8/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
else{
if(((ds.p=0x00E1EA38/*l490c28/string.e*/),((int32_t)(/*IC*/(T2)(r3decimal_value(&ds,_cc))))<=(_bound))){
(ds.p=0x00E1EB12/*l491c9/string.e*/);
_state=/*IC*/(T2)(INT8_C(5));
}
else{
(ds.p=0x00E1ED12/*l493c9/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
}
}
else if(((ds.p=0x00E1F020/*l496c16/string.e*/),r3is_separator(&ds,_cc))){
(ds.p=0x00E1F10E/*l497c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(5));
}
else{
(ds.p=0x00E1F30E/*l499c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
break;
case 5:
if(((ds.p=0x00E1F618/*l502c12/string.e*/),r3is_separator(&ds,_cc))){
}
else{
(ds.p=0x00E1F80E/*l504c7/string.e*/);
_state=/*IC*/(T2)(INT8_C(2));
}
break;
default:;
error1("Invalid inspect (nothing selected).",0x00E1BF0A/*l447c5/string.e*/);
}
}/*INSPECT]*/
(ds.p=0x00E1FB0A/*l507c5/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
}
(ds.p=0x00E1FD08/*l509c4/string.e*/);
R=((T6)(((int32_t)(_state))>=(/*IC*/(T2)(INT8_C(3)))));
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/void r7clear_count(se_dump_stack*caller,T7* C){
T2 o7_1124_15=0;
void**locals[1];
static se_frame_descriptor fd={"clear_count"" STRING",1,1,"%R7%old value%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E45A04/*l1114c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&o7_1124_15;
set_dump_stack_top(&ds);/*link*/
o7_1124_15=(/*RF2*/(C)->_capacity/*i3p*/);
(ds.p=0x00E46108/*l1121c4/string.e*/);
/*SFN*/(C->_count/*i3p*/)=/*IC*/(T2)(INT8_C(0));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E4631C/*l1123c14/string.e*/);
ac_ens(((/*RF2*/(C)->_count/*i3p*/))==(INT8_C(0)),"is_empty");
(ds.p=0x00E46408/*l1124c4/string.e*/);
ac_ens(((/*RF2*/(C)->_capacity/*i3p*/))==(o7_1124_15),"capacity = old capacity");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/void r7extend(se_dump_stack*caller,T7* C,T3 a1){
T2 o7_1417_16=0;
void**locals[2];
static se_frame_descriptor fd={"add_last"" STRING",1,2,"%R7%c%E3%old value%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E57E04/*l1406c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&o7_1417_16;
set_dump_stack_top(&ds);/*link*/
o7_1417_16=(/*RF2*/(C)->_count/*i3p*/);
if(((ds.p=0x00E5830E/*l1411c7/string.e*/),((/*RF2*/(C)->_count/*i3p*/))==((/*RF2*/(C)->_capacity/*i3p*/)))){
(ds.p=0x00E5840A/*l1412c5/string.e*/);
r7ensure_capacity(&ds,C,r2_ix_43(&ds,(/*RF2*/(C)->_count/*i3p*/),/*IC*/(T2)(INT8_C(1))));
}
(ds.p=0x00E58618/*l1414c12/string.e*/);
((/*RF2*/(C)->_storage/*i3p*/))[(/*RF2*/(C)->_count/*i3p*/)]=(a1);
(ds.p=0x00E58708/*l1415c4/string.e*/);
/*SFN*/(C->_count/*i3p*/)=r2_ix_43(&ds,(/*RF2*/(C)->_count/*i3p*/),/*IC*/(T2)(INT8_C(1)));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E58908/*l1417c4/string.e*/);
ac_ens(((/*RF2*/(C)->_count/*i3p*/))==(r2_ix_43(&ds,/*IC*/(T2)(INT8_C(1)),o7_1417_16)),"count = 1 + old count");
(ds.p=0x00E58A08/*l1418c4/string.e*/);
ac_ens((r7item(&ds,C,(/*RF2*/(C)->_count/*i3p*/)))==(a1),"item(count) = c");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/T6 r7has(se_dump_stack*caller,T7* C,T3 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"has"" STRING",1,2,"%R7%c%E3%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E13304/*l307c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x00E13808/*l312c4/string.e*/);
R=((T6)(r9fast_has(&ds,(/*RF2*/(C)->_storage/*i3p*/),a1,r2_ix_45(&ds,(/*RF2*/(C)->_count/*i3p*/),/*IC*/(T2)(INT8_C(1))))));
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/void r7ensure_capacity(se_dump_stack*caller,T7* C,T2 a1){
T2 _new_capacity=0;
void**locals[2];
static se_frame_descriptor fd={"ensure_capacity"" STRING",1,2,"%R7%needed_capacity%E2%new_capacity%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E87C04/*l2172c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&_new_capacity;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E87E28/*l2174c20/string.e*/);
ac_req(((int32_t)(a1))>=(/*IC*/(T2)(INT8_C(0))),"needed_capacity >= 0");
fd.assertion_flag=1;
}
if(((ds.p=0x00E8821E/*l2178c15/string.e*/),r9is_null(&ds,(/*RF2*/(C)->_storage/*i3p*/)))){
(ds.p=0x00E8830A/*l2179c5/string.e*/);
_new_capacity=r2max(&ds,a1,/*IC*/(T2)(INT8_C(32)));
(ds.p=0x00E8840A/*l2180c5/string.e*/);
/*SFN*/(C->_storage/*i3p*/)=new9(_new_capacity);
(ds.p=0x00E8850A/*l2181c5/string.e*/);
/*SFN*/(C->_capacity/*i3p*/)=_new_capacity;
}
else if(((ds.p=0x00E88628/*l2182c20/string.e*/),((int32_t)((/*RF2*/(C)->_capacity/*i3p*/)))<(a1))){
(ds.p=0x00E8870A/*l2183c5/string.e*/);
_new_capacity=r2max(&ds,a1,((int32_t)((/*RF2*/(C)->_capacity/*i3p*/)))*(/*IC*/(T2)(INT8_C(2))));
(ds.p=0x00E8880A/*l2184c5/string.e*/);
/*SFN*/(C->_storage/*i3p*/)=r9realloc(&ds,(/*RF2*/(C)->_storage/*i3p*/),(/*RF2*/(C)->_capacity/*i3p*/),_new_capacity);
(ds.p=0x00E8890A/*l2185c5/string.e*/);
/*SFN*/(C->_capacity/*i3p*/)=_new_capacity;
}
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E88C1A/*l2188c13/string.e*/);
ac_ens(((int32_t)((/*RF2*/(C)->_capacity/*i3p*/)))>=(a1),"capacity >= needed_capacity");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/void r7make(se_dump_stack*caller,T7* C,T2 a1){
void**locals[1];
static se_frame_descriptor fd={"make"" STRING",1,1,"%R7%needed_capacity%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E04304/*l67c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E0464E/*l70c39/string.e*/);
ac_req(((int32_t)(a1))>=(/*IC*/(T2)(INT8_C(0))),"non_negative_size");
fd.assertion_flag=1;
}
if(((ds.p=0x00E0482E/*l72c23/string.e*/),((int32_t)(a1))>(/*IC*/(T2)(INT8_C(0))))){
if(((ds.p=0x00E04922/*l73c17/string.e*/),((int32_t)((/*RF2*/(C)->_capacity/*i3p*/)))<(a1))){
(ds.p=0x00E04A0C/*l74c6/string.e*/);
/*SFN*/(C->_storage/*i3p*/)=new9(a1);
(ds.p=0x00E04B0C/*l75c6/string.e*/);
/*SFN*/(C->_capacity/*i3p*/)=a1;
}
}
(ds.p=0x00E04E08/*l78c4/string.e*/);
/*SFN*/(C->_count/*i3p*/)=/*IC*/(T2)(INT8_C(0));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E05028/*l80c20/string.e*/);
ac_ens(((int32_t)(a1))<=((/*RF2*/(C)->_capacity/*i3p*/)),"needed_capacity <= capacity");
(ds.p=0x00E05124/*l81c18/string.e*/);
ac_ens(((/*RF2*/(C)->_count/*i3p*/))==(INT8_C(0)),"empty_string");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/T2 r7to_integer(se_dump_stack*caller,T7* C){
T2 R=0;
T2 _i=0;
T3 _cc=0;
T6 _negative=0;
void**locals[4];
static se_frame_descriptor fd={"to_integer"" STRING",1,4,"%R7%Result%E2%i%E2%cc%E3%negative%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E20004/*l512c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
locals[1]=(void**)&_i;
locals[2]=(void**)&_cc;
locals[3]=(void**)&_negative;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E20308/*l515c4/string.e*/);
ac_req(r7is_integer(&ds,C),"is_integer");
fd.assertion_flag=1;
}
{int c=0;int v=0;
(ds.p=0x00E2080A/*l520c5/string.e*/);
_i=/*IC*/(T2)(INT8_C(1));
while (!(((ds.p=0x00E20C0A/*l524c5/string.e*/),r6_px_not(&ds,(T6)(r3is_separator(&ds,r7item(&ds,C,_i)))))))
{
(ds.p=0x00E20A16/*l522c11/string.e*/);
v=ac_lvc(c++,v,r2_ix_45(&ds,(/*RF2*/(C)->_count/*i3p*/),_i));
(ds.p=0x00E20E0A/*l526c5/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
}
(ds.p=0x00E21008/*l528c4/string.e*/);
_cc=r7item(&ds,C,_i);
(ds.p=0x00E21108/*l529c4/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
if(((ds.p=0x00E2120E/*l530c7/string.e*/),(_cc)==(((T3)'\053')))){
(ds.p=0x00E2130A/*l531c5/string.e*/);
_cc=r7item(&ds,C,_i);
(ds.p=0x00E2140A/*l532c5/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
else if(((ds.p=0x00E21516/*l533c11/string.e*/),(_cc)==(((T3)'\055')))){
(ds.p=0x00E2160A/*l534c5/string.e*/);
_negative=((T6)(1));
(ds.p=0x00E2170A/*l535c5/string.e*/);
_cc=r7item(&ds,C,_i);
(ds.p=0x00E2180A/*l536c5/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
(ds.p=0x00E21B10/*l539c8/string.e*/);
ac_civ(r3is_digit(&ds,_cc),"cc.is_digit");
(ds.p=0x00E21D08/*l541c4/string.e*/);
R=/*IC*/(T2)(r1_px_45(&ds,r3value(&ds,_cc)));
{int c=0;int v=0;
while (!(((ds.p=0x00E2220E/*l546c7/string.e*/),((int32_t)(_i))>((/*RF2*/(C)->_count/*i3p*/)))))
{
(ds.p=0x00E22016/*l544c11/string.e*/);
v=ac_lvc(c++,v,r2_ix_45(&ds,(/*RF2*/(C)->_count/*i3p*/),_i));
(ds.p=0x00E2240A/*l548c5/string.e*/);
_cc=r7item(&ds,C,_i);
if(((ds.p=0x00E22516/*l549c11/string.e*/),r3is_digit(&ds,_cc))){
(ds.p=0x00E2260C/*l550c6/string.e*/);
R=r2_ix_45(&ds,r2_ix_42(&ds,/*IC*/(T2)(INT8_C(10)),R),/*IC*/(T2)(r3decimal_value(&ds,_cc)));
}
else{
(ds.p=0x00E22914/*l553c10/string.e*/);
ac_civ(r3is_separator(&ds,_cc),"cc.is_separator");
(ds.p=0x00E22B0C/*l555c6/string.e*/);
_i=(/*RF2*/(C)->_count/*i3p*/);
}
(ds.p=0x00E22D0A/*l557c5/string.e*/);
_i=r2_ix_43(&ds,_i,/*IC*/(T2)(INT8_C(1)));
}
}
if(((ds.p=0x00E22F0E/*l559c7/string.e*/),_negative)){
}
else{
(ds.p=0x00E2310A/*l561c5/string.e*/);
R=r2_px_45(&ds,R);
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/T2 r7count(se_dump_stack*caller,T7* C){
T2 R=0;
void**locals[1];
static se_frame_descriptor fd={"count"" STRING",1,1,"%R7%Result%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E02904/*l41c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
R=C->_count/*i3p*/;
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04203620/*l54c16/traversable.e*/);
ac_ens((R)==(r2_ix_43(&ds,r2_ix_45(&ds,r7upper(&ds,C),/*RF1lower*/INT32_C(1)),/*IC*/(T2)(INT8_C(1)))),"definition");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/void r7swap(se_dump_stack*caller,T7* C,T2 a1,T2 a2){
T3 _tmp=0;
T3 o7_1326_15=0;
T3 o7_1327_15=0;
void**locals[5];
static se_frame_descriptor fd={"swap"" STRING",1,5,"%R7%i1%E2%i2%E2%tmp%E3%old value%E3%old value%E3%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E52004/*l1312c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
locals[2]=(void**)&_tmp;
locals[3]=(void**)&o7_1326_15;
locals[4]=(void**)&o7_1327_15;
set_dump_stack_top(&ds);/*link*/
o7_1326_15=r7item(&ds,C,a2);
o7_1327_15=r7item(&ds,C,a1);
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E52508/*l1317c4/string.e*/);
ac_req(r7valid_index(&ds,C,a1),"valid_index(i1)");
(ds.p=0x00E52608/*l1318c4/string.e*/);
ac_req(r7valid_index(&ds,C,a2),"valid_index(i2)");
fd.assertion_flag=1;
}
(ds.p=0x00E52A08/*l1322c4/string.e*/);
_tmp=r7item(&ds,C,a1);
(ds.p=0x00E52B08/*l1323c4/string.e*/);
r7put(&ds,C,r7item(&ds,C,a2),a1);
(ds.p=0x00E52C08/*l1324c4/string.e*/);
r7put(&ds,C,_tmp,a2);
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E52E08/*l1326c4/string.e*/);
ac_ens((r7item(&ds,C,a1))==(o7_1326_15),"item(i1) = old item(i2)");
(ds.p=0x00E52F08/*l1327c4/string.e*/);
ac_ens((r7item(&ds,C,a2))==(o7_1327_15),"item(i2) = old item(i1)");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/

/*STRING*/T2 r7upper(se_dump_stack*caller,T7* C){
T2 R=0;
void**locals[1];
static se_frame_descriptor fd={"upper"" STRING",1,1,"%R7%Result%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E03704/*l55c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x00E03D08/*l61c4/string.e*/);
R=(/*RF2*/(C)->_count/*i3p*/);
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E03F08/*l63c4/string.e*/);
ac_ens((R)==((/*RF2*/(C)->_count/*i3p*/)),"Result = count");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/T6 r7valid_index(se_dump_stack*caller,T7* C,T2 a1){
T6 R=0;
void**locals[2];
static se_frame_descriptor fd={"valid_index"" STRING",1,2,"%R7%i%E2%Result%E6%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x04202504/*l37c2/traversable.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
(ds.p=0x04202A08/*l42c4/traversable.e*/);
R=((T6)((T6)((((int32_t)(/*RF1lower*/INT32_C(1)))<=(a1))&&((T6)(((int32_t)(a1))<=(r7upper(&ds,C)))))));
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04202C20/*l44c16/traversable.e*/);
ac_ens((R)==(r6_ix_and(&ds,(T6)(((int32_t)(/*RF1lower*/INT32_C(1)))<=(a1)),(T6)(((int32_t)(a1))<=(r7upper(&ds,C))))),"definition");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/T3 r7item(se_dump_stack*caller,T7* C,T2 a1){
T3 R=0;
void**locals[2];
static se_frame_descriptor fd={"item"" STRING",1,2,"%R7%i%E2%Result%E3%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E07004/*l112c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&R;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x04204808/*l72c4/traversable.e*/);
ac_req(r7valid_index(&ds,C,a1),"valid_index(i)");
fd.assertion_flag=1;
}
(ds.p=0x00E07508/*l117c4/string.e*/);
R=((/*RF2*/(C)->_storage/*i3p*/))[r2_ix_45(&ds,a1,/*IC*/(T2)(INT8_C(1)))];
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

/*STRING*/void r7put(se_dump_stack*caller,T7* C,T3 a1,T2 a2){
void**locals[2];
static se_frame_descriptor fd={"put"" STRING",1,2,"%R7%c%E3%i%E2%",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=(void*)&C;
ds.p=0x00E51404/*l1300c2/string.e*/;
ds.caller=caller;
ds.locals=locals;
ds.exception_origin=NULL;
locals[0]=(void**)&a1;
locals[1]=(void**)&a2;
set_dump_stack_top(&ds);/*link*/
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E51922/*l1305c17/string.e*/);
ac_req(r7valid_index(&ds,C,a2),"valid_index");
fd.assertion_flag=1;
}
(ds.p=0x00E51B18/*l1307c12/string.e*/);
((/*RF2*/(C)->_storage/*i3p*/))[r2_ix_45(&ds,a2,/*IC*/(T2)(INT8_C(1)))]=(a1);
if(fd.assertion_flag){
fd.assertion_flag=0;
(ds.p=0x00E51D08/*l1309c4/string.e*/);
ac_ens((r7item(&ds,C,a2))==(a1),"item(i) = c");
fd.assertion_flag=1;
}
if(se_rci(caller,C))se_i7(&ds,C);
set_dump_stack_top(caller);/*unlink*/
}/*--*/
se_frame_descriptor se_ifd7={"invariant STRING",1,0,"%R7%",1};

T7*se_i7(se_dump_stack*caller,T7*C){
se_dump_stack ds;
ds.fd=&se_ifd7;
ds.current=((void*)&C);
ds.p=0x00E8AD02/*l2221c1/string.e*/;
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
se_dst=&ds;/*link*/
if(ds.fd->assertion_flag){
ds.fd->assertion_flag=0;
(ds.p=0x00E8AE08/*l2222c4/string.e*/);
ac_inv(((int32_t)(/*IC*/(T2)(INT8_C(0))))<=((/*RF2*/(C)->_count/*i3p*/)),"0 <= count");
(ds.p=0x00E8AF10/*l2223c8/string.e*/);
ac_inv(((int32_t)((/*RF2*/(C)->_count/*i3p*/)))<=((/*RF2*/(C)->_capacity/*i3p*/)),"count <= capacity");
(ds.p=0x00E8B01E/*l2224c15/string.e*/);
ac_inv((T6)((!(((int32_t)((/*RF2*/(C)->_capacity/*i3p*/)))>(/*IC*/(T2)(INT8_C(0)))))||((T6)(r9is_not_null(&ds,(/*RF2*/(C)->_storage/*i3p*/))))),"capacity > 0 implies storage.is_not_null");
ds.fd->assertion_flag=1;
}
se_dst=caller;/*unlink*/
return C;
}/*--*/
T0*ms54_117797837;

T0*se_ms(int c,char*e){
/* Allocate a Manifest STRING.*/
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

T0*se_string(char*e){
/* Allocate an Eiffel STRING by copying C char*e */
int c=strlen(e);
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

void se_msi1(void){
ms54_117797837=se_ms(10,s54_117797837);
}/*--*/

void manifest_string_mark1(void){
gc_mark7((T7*)ms54_117797837);
}/*--*/

void once_function_mark(void){
/*NON_VOID_NO_DISPATCH:*/
/*Ordinary once functions:*/
if(NULL!=oBC26command_arguments)gc_mark123((T123*)(oBC26command_arguments));
if(NULL!=oBC13io)gc_mark41((T41*)(oBC13io));
if(NULL!=oBC31tmp_string)gc_mark7((T7*)(oBC31tmp_string));
if(NULL!=oBC13std_output)gc_mark48((T48*)(oBC13std_output));
if(NULL!=oBC13std_input)gc_mark49((T49*)(oBC13std_input));
}/*--*/

void gc_start(void){
if(gc_is_off)return;
if(garbage_delayed())return;
handle(SE_HANDLE_ENTER_GC,NULL);
gcmt_tail_addr=(((char*)(gcmt[gcmt_used-1]))+(gcmt[gcmt_used-1])->size);
((gc25*)eiffel_root_object)->header.flag=FSOH_UNMARKED;
if(na_env124.store_left>0){
na_env124.store->header.size=na_env124.store_left;
na_env124.store->header.magic_flag=RSOH_FREE;
na_env124.store_left=0;
}
na_env124.chunk_list=NULL;
na_env124.store_chunk=NULL;
if(na_env126.store_left>0){
na_env126.store->header.size=na_env126.store_left;
na_env126.store->header.magic_flag=RSOH_FREE;
na_env126.store_left=0;
}
na_env126.chunk_list=NULL;
na_env126.store_chunk=NULL;
gc_free48=(void*)0;
gc_free49=(void*)0;
gc_free123=(void*)0;
gc_free125=(void*)0;
gc_free41=(void*)0;
gc_free25=(void*)0;
if(na_env9.store_left>0){
na_env9.store->header.size=na_env9.store_left;
na_env9.store->header.magic_flag=RSOH_FREE;
na_env9.store_left=0;
}
na_env9.chunk_list=NULL;
na_env9.store_chunk=NULL;
gc_free7=(void*)0;
gc_mark25(eiffel_root_object);
manifest_string_mark1();
once_function_mark();
{int i=SE_MAXID-1;
while(i>=0){
if(g[i]!=NULL)gc_mark7(g[i]);
i--;}
}
{int i=SE_MAXID-1;
while(i>=0){
if(t[i]!=NULL)gc_mark7(t[i]);
i--;}
}
mark_stack_and_registers();
gc_sweep();
collector_counter++;
handle(SE_HANDLE_EXIT_GC,NULL);
}/*--*/
na_env na_env124={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark124};
na_env na_env126={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark126};
gc48*store48=(void*)0;
int store_left48=0;
fsoc*store_chunk48=(void*)0;
gc48*gc_free48=(void*)0;
gc49*store49=(void*)0;
int store_left49=0;
fsoc*store_chunk49=(void*)0;
gc49*gc_free49=(void*)0;
gc123*store123=(void*)0;
int store_left123=0;
fsoc*store_chunk123=(void*)0;
gc123*gc_free123=(void*)0;
gc125*store125=(void*)0;
int store_left125=0;
fsoc*store_chunk125=(void*)0;
gc125*gc_free125=(void*)0;
gc41*store41=(void*)0;
int store_left41=0;
fsoc*store_chunk41=(void*)0;
gc41*gc_free41=(void*)0;
gc25*store25=(void*)0;
int store_left25=0;
fsoc*store_chunk25=(void*)0;
gc25*gc_free25=(void*)0;
na_env na_env9={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark9};
gc7*store7=(void*)0;
int store_left7=0;
fsoc*store_chunk7=(void*)0;
gc7*gc_free7=(void*)0;

void gc_mark124(T124 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
{rsoh*h=((rsoh*)o)-1;
 if((h->header.magic_flag)==RSOH_UNMARKED){
    h->header.magic_flag=RSOH_MARKED;
    {T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark7((T7*)(e));
}}}}
}/*--*/

T124 new124(unsigned int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env124.store_left)){
rsoh*r=na_env124.store;
na_env124.store_left-=size;
if(na_env124.store_left>sizeof(rsoh)){
r->header.size=size;
na_env124.store=((rsoh*)(((char*)(na_env124.store))+size));
}
else {
r->header.size=size+na_env124.store_left;
na_env124.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T124)(r+1));
}
return((T124)new_na(&na_env124,size));
}/*--*/

void gc_mark126(T126 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
(((rsoh*)o)-1)->header.magic_flag=RSOH_MARKED;
}/*--*/

T126 new126(unsigned int size){
size=(size*sizeof(T2))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env126.store_left)){
rsoh*r=na_env126.store;
na_env126.store_left-=size;
if(na_env126.store_left>sizeof(rsoh)){
r->header.size=size;
na_env126.store=((rsoh*)(((char*)(na_env126.store))+size));
}
else {
r->header.size=size+na_env126.store_left;
na_env126.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T126)(r+1));
}
return((T126)new_na(&na_env126,size));
}/*--*/

void gc_sweep48(fsoc*c){
gc48*o1,*o2;
o1=((gc48*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store48;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
}
else{
int dead=1;
gc48* old_gc_free = gc_free48;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
if (dead){
gc_free48 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark48(T48*o){
se_gc_check_id(o,48);
{
if(((gc48*)o)->header.flag==FSOH_UNMARKED){
((gc48*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/

void gc_align_mark48(fsoc*c,gc48*p){
gc48*b=((gc48*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store48)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T48*o=(&(p->object));
((gc48*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/
fsoc H48={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark48,
(void(*)(mch*))gc_sweep48},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc48))-1)};

T48*new48(void){
gc48*n;
fsoc*c;
if(store_left48>1){
store_left48--;
n=store48++;
}
else if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else if(store_left48==1){
store_left48=0;
store_chunk48->header.state_type=FSO_USED_CHUNK;
n=store48++;
}
else{
c=gc_fsoc_get1();
if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk48=c;
*store_chunk48=H48;
store48=((gc48*)(&(store_chunk48->first_object)));
store_left48=H48.count_minus_one;
n=store48++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M48;
return((T48*)n);
}/*--*/

void gc_sweep49(fsoc*c){
gc49*o1,*o2;
o1=((gc49*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store49;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free49;
gc_free49=o1;
}
}
}
else{
int dead=1;
gc49* old_gc_free = gc_free49;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free49;
gc_free49=o1;
}
}
if (dead){
gc_free49 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark49(T49*o){
se_gc_check_id(o,49);
{
if(((gc49*)o)->header.flag==FSOH_UNMARKED){
((gc49*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/

void gc_align_mark49(fsoc*c,gc49*p){
gc49*b=((gc49*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store49)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T49*o=(&(p->object));
((gc49*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/
fsoc H49={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark49,
(void(*)(mch*))gc_sweep49},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc49))-1)};

T49*new49(void){
gc49*n;
fsoc*c;
if(store_left49>1){
store_left49--;
n=store49++;
}
else if(gc_free49!=NULL){
n=gc_free49;
gc_free49=n->header.next;
}
else if(store_left49==1){
store_left49=0;
store_chunk49->header.state_type=FSO_USED_CHUNK;
n=store49++;
}
else{
c=gc_fsoc_get1();
if(gc_free49!=NULL){
n=gc_free49;
gc_free49=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk49=c;
*store_chunk49=H49;
store49=((gc49*)(&(store_chunk49->first_object)));
store_left49=H49.count_minus_one;
n=store49++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M49;
return((T49*)n);
}/*--*/

void gc_sweep123(fsoc*c){
gc123*o1,*o2;
o1=((gc123*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store123;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free123;
gc_free123=o1;
}
}
}
else{
int dead=1;
gc123* old_gc_free = gc_free123;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free123;
gc_free123=o1;
}
}
if (dead){
gc_free123 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark123(T123*o){
se_gc_check_id(o,123);
{
if(((gc123*)o)->header.flag==FSOH_UNMARKED){
((gc123*)o)->header.flag=FSOH_MARKED;
/*i3p*/{
T124 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r123mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/

void gc_align_mark123(fsoc*c,gc123*p){
gc123*b=((gc123*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store123)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T123*o=(&(p->object));
((gc123*)o)->header.flag=FSOH_MARKED;
/*i3p*/{
T124 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r123mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/
fsoc H123={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark123,
(void(*)(mch*))gc_sweep123},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc123))-1)};

T123*new123(void){
gc123*n;
fsoc*c;
if(store_left123>1){
store_left123--;
n=store123++;
}
else if(gc_free123!=NULL){
n=gc_free123;
gc_free123=n->header.next;
}
else if(store_left123==1){
store_left123=0;
store_chunk123->header.state_type=FSO_USED_CHUNK;
n=store123++;
}
else{
c=gc_fsoc_get1();
if(gc_free123!=NULL){
n=gc_free123;
gc_free123=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk123=c;
*store_chunk123=H123;
store123=((gc123*)(&(store_chunk123->first_object)));
store_left123=H123.count_minus_one;
n=store123++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M123;
return((T123*)n);
}/*--*/

void gc_sweep125(fsoc*c){
gc125*o1,*o2;
o1=((gc125*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store125;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free125;
gc_free125=o1;
}
}
}
else{
int dead=1;
gc125* old_gc_free = gc_free125;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free125;
gc_free125=o1;
}
}
if (dead){
gc_free125 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark125(T125*o){
se_gc_check_id(o,125);
{
if(((gc125*)o)->header.flag==FSOH_UNMARKED){
((gc125*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_storage)gc_mark126((o->_storage));
}
}
}/*--*/

void gc_align_mark125(fsoc*c,gc125*p){
gc125*b=((gc125*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store125)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T125*o=(&(p->object));
((gc125*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_storage)gc_mark126((o->_storage));
}
}
}/*--*/
fsoc H125={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark125,
(void(*)(mch*))gc_sweep125},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc125))-1)};

T125*new125(void){
gc125*n;
fsoc*c;
if(store_left125>1){
store_left125--;
n=store125++;
}
else if(gc_free125!=NULL){
n=gc_free125;
gc_free125=n->header.next;
}
else if(store_left125==1){
store_left125=0;
store_chunk125->header.state_type=FSO_USED_CHUNK;
n=store125++;
}
else{
c=gc_fsoc_get1();
if(gc_free125!=NULL){
n=gc_free125;
gc_free125=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk125=c;
*store_chunk125=H125;
store125=((gc125*)(&(store_chunk125->first_object)));
store_left125=H125.count_minus_one;
n=store125++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M125;
return((T125*)n);
}/*--*/

void gc_sweep41(fsoc*c){
gc41*o1,*o2;
o1=((gc41*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store41;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free41;
gc_free41=o1;
}
}
}
else{
int dead=1;
gc41* old_gc_free = gc_free41;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free41;
gc_free41=o1;
}
}
if (dead){
gc_free41 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark41(T41*o){
se_gc_check_id(o,41);
{
if(((gc41*)o)->header.flag==FSOH_UNMARKED){
((gc41*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/

void gc_align_mark41(fsoc*c,gc41*p){
gc41*b=((gc41*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store41)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T41*o=(&(p->object));
((gc41*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/
fsoc H41={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark41,
(void(*)(mch*))gc_sweep41},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc41))-1)};

T41*new41(void){
gc41*n;
fsoc*c;
if(store_left41>1){
store_left41--;
n=store41++;
}
else if(gc_free41!=NULL){
n=gc_free41;
gc_free41=n->header.next;
}
else if(store_left41==1){
store_left41=0;
store_chunk41->header.state_type=FSO_USED_CHUNK;
n=store41++;
}
else{
c=gc_fsoc_get1();
if(gc_free41!=NULL){
n=gc_free41;
gc_free41=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk41=c;
*store_chunk41=H41;
store41=((gc41*)(&(store_chunk41->first_object)));
store_left41=H41.count_minus_one;
n=store41++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M41;
return((T41*)n);
}/*--*/

void gc_sweep25(fsoc*c){
gc25*o1,*o2;
o1=((gc25*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store25;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
}
else{
int dead=1;
gc25* old_gc_free = gc_free25;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
if (dead){
gc_free25 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark25(T25*o){
se_gc_check_id(o,25);
{
((gc25*)o)->header.flag=FSOH_MARKED;
}
}/*--*/

void gc_align_mark25(fsoc*c,gc25*p){
gc25*b=((gc25*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store25)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T25*o=(&(p->object));
((gc25*)o)->header.flag=FSOH_MARKED;
}
}
}/*--*/
fsoc H25={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark25,
(void(*)(mch*))gc_sweep25},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc25))-1)};

T25*new25(void){
gc25*n;
fsoc*c;
if(store_left25>1){
store_left25--;
n=store25++;
}
else if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else if(store_left25==1){
store_left25=0;
store_chunk25->header.state_type=FSO_USED_CHUNK;
n=store25++;
}
else{
c=gc_fsoc_get1();
if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk25=c;
*store_chunk25=H25;
store25=((gc25*)(&(store_chunk25->first_object)));
store_left25=H25.count_minus_one;
n=store25++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M25;
return((T25*)n);
}/*--*/

void gc_mark9(T9 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
(((rsoh*)o)-1)->header.magic_flag=RSOH_MARKED;
}/*--*/

T9 new9(unsigned int size){
size=(size*sizeof(T3))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env9.store_left)){
rsoh*r=na_env9.store;
na_env9.store_left-=size;
if(na_env9.store_left>sizeof(rsoh)){
r->header.size=size;
na_env9.store=((rsoh*)(((char*)(na_env9.store))+size));
}
else {
r->header.size=size+na_env9.store_left;
na_env9.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T9)(r+1));
}
return((T9)new_na(&na_env9,size));
}/*--*/

void gc_sweep7(fsoc*c){
gc7*o1,*o2;
o1=((gc7*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store7;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
}
else{
int dead=1;
gc7* old_gc_free = gc_free7;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
if (dead){
gc_free7 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark7(T7*o){
se_gc_check_id(o,7);
{
if(((gc7*)o)->header.flag==FSOH_UNMARKED){
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/

void gc_align_mark7(fsoc*c,gc7*p){
gc7*b=((gc7*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store7)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T7*o=(&(p->object));
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/
fsoc H7={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark7,
(void(*)(mch*))gc_sweep7},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc7))-1)};

T7*new7(void){
gc7*n;
fsoc*c;
if(store_left7>1){
store_left7--;
n=store7++;
}
else if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else if(store_left7==1){
store_left7=0;
store_chunk7->header.state_type=FSO_USED_CHUNK;
n=store7++;
}
else{
c=gc_fsoc_get1();
if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk7=c;
*store_chunk7=H7;
store7=((gc7*)(&(store_chunk7->first_object)));
store_left7=H7.count_minus_one;
n=store7++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M7;
return((T7*)n);
}/*--*/
T25*eiffel_root_object=(void*)0;
int se_argc;
char**se_argv;
T7*g[130];
T7*t[130];
char*p[130];
void(*se_prinT[130])(FILE*,void*);
int se_strucT[130]={0,sizeof(T1),sizeof(T2),sizeof(T3),0,0,sizeof(T6),sizeof(T7),sizeof(T8),sizeof(T9),sizeof(T10),sizeof(T11),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T25),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T41),
0,
0,
0,
0,
0,
0,
sizeof(T48),
sizeof(T49),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T123),
sizeof(T124),
sizeof(T125),
sizeof(T126)};

void se_atexit(void){
se_frame_descriptor fd={"<atexit wrapper>",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.p=0;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
r48se_atexit(&ds,NULL/*Unused Target*/);
}/*--*/

void initialize_eiffel_runtime(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor irfd={"<runtime init>",0,0,"",1};
se_dump_stack ds = {NULL,NULL,0,NULL,NULL};
ds.fd=&irfd;
set_dump_stack_top(&ds);/*link*/
se_argc=argc;
se_argv=argv;
atexit(se_atexit);
gcmt=((mch**)se_malloc((gcmt_max+1)*sizeof(void*)));
#ifdef FIXED_STACK_BOTTOM
if (!stack_bottom) stack_bottom=((void**)(void*)(&argc));
#endif
p[0]="???";
p[25]="/comptes/E165896X/Documents/M1/meth_form/tp1/Sources_TP1/fibonacci/fibonacci.e";
p[101]="/usr/local/opt/SmartEiffel/lib/kernel/procedure.e";
p[95]="/usr/local/opt/SmartEiffel/lib/kernel/memory.e";
p[15]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[16]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[69]="/usr/local/opt/SmartEiffel/lib/kernel/routine.e";
p[17]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[18]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[19]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[20]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[21]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[22]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[23]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[14]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[24]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[8]="/usr/local/opt/SmartEiffel/lib/kernel/pointer.e";
p[100]="/usr/local/opt/SmartEiffel/lib/kernel/reference.e";
p[26]="/usr/local/opt/SmartEiffel/lib/kernel/arguments.e";
p[68]="/usr/local/opt/SmartEiffel/lib/kernel/function.e";
p[6]="/usr/local/opt/SmartEiffel/lib/kernel/boolean.e";
p[58]="/usr/local/opt/SmartEiffel/lib/kernel/safe_equal.e";
p[13]="/usr/local/opt/SmartEiffel/lib/kernel/any.e";
p[102]="/usr/local/opt/SmartEiffel/lib/kernel/weak_reference.e";
p[37]="/usr/local/opt/SmartEiffel/lib/kernel/platform.e";
p[75]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals_handler.e";
p[86]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_internals.e";
p[46]="/usr/local/opt/SmartEiffel/lib/kernel/internal/typed_internals.e";
p[52]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_collector.e";
p[47]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals.e";
p[51]="/usr/local/opt/SmartEiffel/lib/storage/collection.e";
p[50]="/usr/local/opt/SmartEiffel/lib/storage/collection/fast_array.e";
p[70]="/usr/local/opt/SmartEiffel/lib/storage/collection/array.e";
p[103]="/usr/local/opt/SmartEiffel/lib/storage/collection/ring_array.e";
p[57]="/usr/local/opt/SmartEiffel/lib/storage/low_level/native_array.e";
p[94]="/usr/local/opt/SmartEiffel/lib/storage/low_level/recycling_pool.e";
p[53]="/usr/local/opt/SmartEiffel/lib/storage/internal/arrayed_collection.e";
p[107]="/usr/local/opt/SmartEiffel/lib/io/directory_notation.e";
p[56]="/usr/local/opt/SmartEiffel/lib/io/filter.e";
p[27]="/usr/local/opt/SmartEiffel/lib/io/output_stream.e";
p[114]="/usr/local/opt/SmartEiffel/lib/io/path_name.e";
p[73]="/usr/local/opt/SmartEiffel/lib/io/filter_input_stream.e";
p[39]="/usr/local/opt/SmartEiffel/lib/io/terminal_output_stream.e";
p[105]="/usr/local/opt/SmartEiffel/lib/io/file_tools.e";
p[43]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_stream.e";
p[42]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_output_stream.e";
p[64]="/usr/local/opt/SmartEiffel/lib/io/filter_output_stream.e";
p[44]="/usr/local/opt/SmartEiffel/lib/io/input_stream.e";
p[28]="/usr/local/opt/SmartEiffel/lib/io/stream.e";
p[63]="/usr/local/opt/SmartEiffel/lib/io/terminal/file.e";
p[62]="/usr/local/opt/SmartEiffel/lib/io/terminal/text_file_read.e";
p[41]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input_output.e";
p[38]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_error.e";
p[49]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input.e";
p[48]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_output.e";
p[45]="/usr/local/opt/SmartEiffel/lib/io/low_level/input_stream_tools.e";
p[31]="/usr/local/opt/SmartEiffel/lib/io/low_level/output_stream_tools.e";
p[40]="/usr/local/opt/SmartEiffel/lib/io/low_level/redirection_tools.e";
p[106]="/usr/local/opt/SmartEiffel/lib/io/low_level/basic_directory.e";
p[116]="/usr/local/opt/SmartEiffel/lib/io/internal/unixish_path_name.e";
p[30]="/usr/local/opt/SmartEiffel/lib/io/internal/filterable.e";
p[113]="/usr/local/opt/SmartEiffel/lib/io/internal/path_joiner.e";
p[115]="/usr/local/opt/SmartEiffel/lib/io/path_name/posix_path_name.e";
p[112]="/usr/local/opt/SmartEiffel/lib/io/path_name/path_name_notation.e";
p[110]="/usr/local/opt/SmartEiffel/lib/io/path_name/macintosh_directory_notation.e";
p[118]="/usr/local/opt/SmartEiffel/lib/io/path_name/openvms_directory_notation.e";
p[121]="/usr/local/opt/SmartEiffel/lib/io/path_name/microsoft_path_name.e";
p[120]="/usr/local/opt/SmartEiffel/lib/io/path_name/windows_directory_notation.e";
p[111]="/usr/local/opt/SmartEiffel/lib/io/path_name/unix_directory_notation.e";
p[119]="/usr/local/opt/SmartEiffel/lib/io/path_name/amiga_directory_notation.e";
p[122]="/usr/local/opt/SmartEiffel/lib/io/path_name/cygwin_directory_notation.e";
p[108]="/usr/local/opt/SmartEiffel/lib/unicode/unicode_string_handler.e";
p[67]="/usr/local/opt/SmartEiffel/lib/iterator/iterator.e";
p[76]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_traversable.e";
p[83]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_unicode_string.e";
p[72]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_string.e";
p[85]="/usr/local/opt/SmartEiffel/lib/misc/mini_parser_buffer.e";
p[84]="/usr/local/opt/SmartEiffel/lib/sequencer/events_set.e";
p[65]="/usr/local/opt/SmartEiffel/lib/sequencer/event_descriptor.e";
p[74]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_read_data_from_stream.e";
p[99]="/usr/local/opt/SmartEiffel/lib/sequencer/events/network_connection_occurred.e";
p[66]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_write_data_to_stream.e";
p[29]="/usr/local/opt/SmartEiffel/lib/abilities/recyclable.e";
p[93]="/usr/local/opt/SmartEiffel/lib/abilities/disposable.e";
p[33]="/usr/local/opt/SmartEiffel/lib/abilities/traversable.e";
p[36]="/usr/local/opt/SmartEiffel/lib/abilities/hashable.e";
p[34]="/usr/local/opt/SmartEiffel/lib/abilities/storable.e";
p[35]="/usr/local/opt/SmartEiffel/lib/abilities/comparable.e";
p[12]="/usr/local/opt/SmartEiffel/lib/numeric/real_extended.e";
p[59]="/usr/local/opt/SmartEiffel/lib/numeric/real_general.e";
p[2]="/usr/local/opt/SmartEiffel/lib/numeric/integer_32.e";
p[60]="/usr/local/opt/SmartEiffel/lib/numeric/number.e";
p[4]="/usr/local/opt/SmartEiffel/lib/numeric/real_32.e";
p[1]="/usr/local/opt/SmartEiffel/lib/numeric/integer_8.e";
p[79]="/usr/local/opt/SmartEiffel/lib/numeric/mutable_big_integer.e";
p[11]="/usr/local/opt/SmartEiffel/lib/numeric/integer_64.e";
p[71]="/usr/local/opt/SmartEiffel/lib/numeric/number_tools.e";
p[54]="/usr/local/opt/SmartEiffel/lib/numeric/integer_general.e";
p[5]="/usr/local/opt/SmartEiffel/lib/numeric/real_64.e";
p[55]="/usr/local/opt/SmartEiffel/lib/numeric/numeric.e";
p[10]="/usr/local/opt/SmartEiffel/lib/numeric/integer_16.e";
p[80]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_with_big_integer_number.e";
p[77]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_64_number.e";
p[78]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_general_number.e";
p[81]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_general_number.e";
p[82]="/usr/local/opt/SmartEiffel/lib/numeric/internal/big_integer_number.e";
p[61]="/usr/local/opt/SmartEiffel/lib/string/unicode_string.e";
p[3]="/usr/local/opt/SmartEiffel/lib/string/character.e";
p[7]="/usr/local/opt/SmartEiffel/lib/string/string.e";
p[32]="/usr/local/opt/SmartEiffel/lib/string/low_level/string_handler.e";
p[109]="/usr/local/opt/SmartEiffel/lib/time/time_formatter.e";
p[91]="/usr/local/opt/SmartEiffel/lib/time/time.e";
p[87]="/usr/local/opt/SmartEiffel/lib/time/microsecond_time.e";
p[96]="/usr/local/opt/SmartEiffel/lib/net/access.e";
p[98]="/usr/local/opt/SmartEiffel/lib/net/socket_input_output_stream.e";
p[88]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_server.e";
p[104]="/usr/local/opt/SmartEiffel/lib/net/low_level/client_socket_input_output_stream.e";
p[97]="/usr/local/opt/SmartEiffel/lib/net/low_level/server_socket_input_output_stream.e";
p[89]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_plug_in.e";
p[90]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_handler.e";
p[92]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket.e";
p[117]="/usr/local/opt/SmartEiffel/lib/exec/system.e";
se_prinT[126]=((void(*)(FILE*,void*))se_prinT126);
p[126]=p[57];
se_prinT[125]=((void(*)(FILE*,void*))se_prinT125);
p[125]=p[70];
se_prinT[124]=((void(*)(FILE*,void*))se_prinT124);
p[124]=p[57];
se_prinT[123]=((void(*)(FILE*,void*))se_prinT123);
p[123]=p[50];
se_prinT[49]=((void(*)(FILE*,void*))se_prinT49);
se_prinT[48]=((void(*)(FILE*,void*))se_prinT48);
se_prinT[41]=((void(*)(FILE*,void*))se_prinT41);
se_prinT[25]=((void(*)(FILE*,void*))se_prinT25);
se_prinT[11]=((void(*)(FILE*,void*))se_prinT11);
se_prinT[10]=((void(*)(FILE*,void*))se_prinT10);
se_prinT[9]=((void(*)(FILE*,void*))se_prinT9);
p[9]=p[57];
se_prinT[8]=((void(*)(FILE*,void*))se_prinT8);
se_prinT[7]=((void(*)(FILE*,void*))se_prinT7);
se_prinT[6]=((void(*)(FILE*,void*))se_prinT6);
se_prinT[3]=((void(*)(FILE*,void*))se_prinT3);
se_prinT[2]=((void(*)(FILE*,void*))se_prinT2);
se_prinT[1]=((void(*)(FILE*,void*))se_prinT1);
g[25]=(T7*)se_string("FIBONACCI");
g[101]=(T7*)se_string("PROCEDURE");
g[95]=(T7*)se_string("MEMORY");
g[15]=(T7*)se_string("TUPLE 1");
g[16]=(T7*)se_string("TUPLE 2");
g[69]=(T7*)se_string("ROUTINE");
g[17]=(T7*)se_string("TUPLE 3");
g[18]=(T7*)se_string("TUPLE 4");
g[19]=(T7*)se_string("TUPLE 5");
g[20]=(T7*)se_string("TUPLE 6");
g[21]=(T7*)se_string("TUPLE 7");
g[22]=(T7*)se_string("TUPLE 8");
g[23]=(T7*)se_string("TUPLE 9");
g[14]=(T7*)se_string("TUPLE");
g[24]=(T7*)se_string("TUPLE 10");
g[8]=(T7*)se_string("POINTER");
g[100]=(T7*)se_string("REFERENCE");
g[26]=(T7*)se_string("ARGUMENTS");
g[68]=(T7*)se_string("FUNCTION");
g[6]=(T7*)se_string("BOOLEAN");
g[58]=(T7*)se_string("SAFE_EQUAL");
g[13]=(T7*)se_string("ANY");
g[102]=(T7*)se_string("WEAK_REFERENCE");
g[37]=(T7*)se_string("PLATFORM");
g[75]=(T7*)se_string("INTERNALS_HANDLER");
g[86]=(T7*)se_string("NATIVE_ARRAY_INTERNALS");
g[46]=(T7*)se_string("TYPED_INTERNALS");
g[52]=(T7*)se_string("NATIVE_ARRAY_COLLECTOR");
g[47]=(T7*)se_string("INTERNALS");
g[51]=(T7*)se_string("COLLECTION");
g[50]=(T7*)se_string("FAST_ARRAY");
g[70]=(T7*)se_string("ARRAY");
g[103]=(T7*)se_string("RING_ARRAY");
g[57]=(T7*)se_string("NATIVE_ARRAY");
g[94]=(T7*)se_string("RECYCLING_POOL");
g[53]=(T7*)se_string("ARRAYED_COLLECTION");
g[107]=(T7*)se_string("DIRECTORY_NOTATION");
g[56]=(T7*)se_string("FILTER");
g[27]=(T7*)se_string("OUTPUT_STREAM");
g[114]=(T7*)se_string("PATH_NAME");
g[73]=(T7*)se_string("FILTER_INPUT_STREAM");
g[39]=(T7*)se_string("TERMINAL_OUTPUT_STREAM");
g[105]=(T7*)se_string("FILE_TOOLS");
g[43]=(T7*)se_string("TERMINAL_INPUT_STREAM");
g[42]=(T7*)se_string("TERMINAL_INPUT_OUTPUT_STREAM");
g[64]=(T7*)se_string("FILTER_OUTPUT_STREAM");
g[44]=(T7*)se_string("INPUT_STREAM");
g[28]=(T7*)se_string("STREAM");
g[63]=(T7*)se_string("FILE");
g[62]=(T7*)se_string("TEXT_FILE_READ");
g[41]=(T7*)se_string("STD_INPUT_OUTPUT");
g[38]=(T7*)se_string("STD_ERROR");
g[49]=(T7*)se_string("STD_INPUT");
g[48]=(T7*)se_string("STD_OUTPUT");
g[45]=(T7*)se_string("INPUT_STREAM_TOOLS");
g[31]=(T7*)se_string("OUTPUT_STREAM_TOOLS");
g[40]=(T7*)se_string("REDIRECTION_TOOLS");
g[106]=(T7*)se_string("BASIC_DIRECTORY");
g[116]=(T7*)se_string("UNIXISH_PATH_NAME");
g[30]=(T7*)se_string("FILTERABLE");
g[113]=(T7*)se_string("PATH_JOINER");
g[115]=(T7*)se_string("POSIX_PATH_NAME");
g[112]=(T7*)se_string("PATH_NAME_NOTATION");
g[110]=(T7*)se_string("MACINTOSH_DIRECTORY_NOTATION");
g[118]=(T7*)se_string("OPENVMS_DIRECTORY_NOTATION");
g[121]=(T7*)se_string("MICROSOFT_PATH_NAME");
g[120]=(T7*)se_string("WINDOWS_DIRECTORY_NOTATION");
g[111]=(T7*)se_string("UNIX_DIRECTORY_NOTATION");
g[119]=(T7*)se_string("AMIGA_DIRECTORY_NOTATION");
g[122]=(T7*)se_string("CYGWIN_DIRECTORY_NOTATION");
g[108]=(T7*)se_string("UNICODE_STRING_HANDLER");
g[67]=(T7*)se_string("ITERATOR");
g[76]=(T7*)se_string("ITERATOR_ON_TRAVERSABLE");
g[83]=(T7*)se_string("ITERATOR_ON_UNICODE_STRING");
g[72]=(T7*)se_string("ITERATOR_ON_STRING");
g[85]=(T7*)se_string("MINI_PARSER_BUFFER");
g[84]=(T7*)se_string("EVENTS_SET");
g[65]=(T7*)se_string("EVENT_DESCRIPTOR");
g[74]=(T7*)se_string("CAN_READ_DATA_FROM_STREAM");
g[99]=(T7*)se_string("NETWORK_CONNECTION_OCCURRED");
g[66]=(T7*)se_string("CAN_WRITE_DATA_TO_STREAM");
g[29]=(T7*)se_string("RECYCLABLE");
g[93]=(T7*)se_string("DISPOSABLE");
g[33]=(T7*)se_string("TRAVERSABLE");
g[36]=(T7*)se_string("HASHABLE");
g[34]=(T7*)se_string("STORABLE");
g[35]=(T7*)se_string("COMPARABLE");
g[12]=(T7*)se_string("REAL_EXTENDED");
g[59]=(T7*)se_string("REAL_GENERAL");
g[2]=(T7*)se_string("INTEGER_32");
g[60]=(T7*)se_string("NUMBER");
g[4]=(T7*)se_string("REAL_32");
g[1]=(T7*)se_string("INTEGER_8");
g[79]=(T7*)se_string("MUTABLE_BIG_INTEGER");
g[11]=(T7*)se_string("INTEGER_64");
g[71]=(T7*)se_string("NUMBER_TOOLS");
g[54]=(T7*)se_string("INTEGER_GENERAL");
g[5]=(T7*)se_string("REAL_64");
g[55]=(T7*)se_string("NUMERIC");
g[10]=(T7*)se_string("INTEGER_16");
g[80]=(T7*)se_string("FRACTION_WITH_BIG_INTEGER_NUMBER");
g[77]=(T7*)se_string("INTEGER_64_NUMBER");
g[78]=(T7*)se_string("INTEGER_GENERAL_NUMBER");
g[81]=(T7*)se_string("FRACTION_GENERAL_NUMBER");
g[82]=(T7*)se_string("BIG_INTEGER_NUMBER");
g[61]=(T7*)se_string("UNICODE_STRING");
g[3]=(T7*)se_string("CHARACTER");
g[7]=(T7*)se_string("STRING");
g[32]=(T7*)se_string("STRING_HANDLER");
g[109]=(T7*)se_string("TIME_FORMATTER");
g[91]=(T7*)se_string("TIME");
g[87]=(T7*)se_string("MICROSECOND_TIME");
g[96]=(T7*)se_string("ACCESS");
g[98]=(T7*)se_string("SOCKET_INPUT_OUTPUT_STREAM");
g[88]=(T7*)se_string("SOCKET_SERVER");
g[104]=(T7*)se_string("CLIENT_SOCKET_INPUT_OUTPUT_STREAM");
g[97]=(T7*)se_string("SERVER_SOCKET_INPUT_OUTPUT_STREAM");
g[89]=(T7*)se_string("SOCKET_PLUG_IN");
g[90]=(T7*)se_string("SOCKET_HANDLER");
g[92]=(T7*)se_string("SOCKET");
g[117]=(T7*)se_string("SYSTEM");
g[126]=g[57];
g[125]=g[70];
g[124]=g[57];
g[123]=g[50];
g[9]=g[57];
t[126]=(T7*)se_string("NATIVE_ARRAY[INTEGER_32]");
t[125]=(T7*)se_string("ARRAY[INTEGER_32]");
t[124]=(T7*)se_string("NATIVE_ARRAY[STRING]");
t[123]=(T7*)se_string("FAST_ARRAY[STRING]");
t[49]=g[49];
t[48]=g[48];
t[41]=g[41];
t[25]=g[25];
t[11]=g[11];
t[10]=g[10];
t[9]=(T7*)se_string("NATIVE_ARRAY[CHARACTER]");
t[8]=g[8];
t[7]=g[7];
t[6]=g[6];
t[3]=g[3];
t[2]=g[2];
t[1]=g[1];
#ifdef SIGINT
signal(SIGINT,se_signal_handler);
#endif
#ifdef SIGTERM
signal(SIGTERM,se_signal_handler);
#endif
#ifdef SIGQUIT
signal(SIGQUIT,se_signal_handler);
#endif
#ifdef SIGILL
signal(SIGILL,se_signal_handler);
#endif
#ifdef SIGABRT
signal(SIGABRT,se_signal_handler);
#endif
#ifdef SIGFPE
signal(SIGFPE,se_signal_handler);
#endif
#ifdef SIGSEGV
signal(SIGSEGV,se_signal_handler);
#endif
#ifdef SIGBUS
signal(SIGBUS,se_signal_handler);
#endif
#ifdef SIGSYS
signal(SIGSYS,se_signal_handler);
#endif
#ifdef SIGTRAP
signal(SIGTRAP,se_signal_handler);
#endif
#ifdef SIGXCPU
signal(SIGXCPU,se_signal_handler);
#endif
#ifdef SIGXFSZ
signal(SIGXFSZ,se_signal_handler);
#endif
se_msi1();
gc_is_off=0;
tmp0=((T0*)(new25()));
eiffel_root_object=((T25*)tmp0);
set_dump_stack_top((void*)0);/*unlink*/
}/*--*/

int main(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor root={"<system root>",1,0,"%R25%",1};
se_dump_stack ds;
stack_bottom=((void**)(void*)(&argc));
initialize_eiffel_runtime(argc,argv);
tmp0=((T0*)eiffel_root_object);
ds.fd=&root;
ds.current=((void*)(&tmp0));
ds.p=0x03200B04/*l11c2/fibonacci.e*/;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
set_dump_stack_top(&ds);/*link*/
r25make(&ds,((T25*)tmp0));
handle(SE_HANDLE_NORMAL_EXIT, NULL);
set_dump_stack_top(NULL);/*unlink*/
exit(0);
return 0;
}/*--*/

#ifdef __cplusplus
}
#endif
